version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=123123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pdmdev
    ports:
      - "5432:5432" 
